# Generated by Django 4.2.13 on 2026-04-19 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('cap', 'Cap'), ('mug', 'Mug'), ('tote', 'Tote Bag'), ('other', 'Other')], default='tshirt', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_label', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('detail', 'Detail')], default='front', max_length=20)),
                ('base_image', models.ImageField(upload_to='products/base/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('print_area_x', models.PositiveIntegerField(default=0, help_text='Left edge of print area (px)')),
                ('print_area_y', models.PositiveIntegerField(default=0, help_text='Top edge of print area (px)')),
                ('print_area_w', models.PositiveIntegerField(default=300, help_text='Width of print area (px)')),
                ('print_area_h', models.PositiveIntegerField(default=300, help_text='Height of print area (px)')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('displacement_map', models.ImageField(blank=True, null=True, upload_to='products/disp_maps/')),
                ('surface_angle_deg', models.FloatField(default=0.0, help_text='Detected surface tilt angle (degrees)')),
                ('perspective_matrix', models.JSONField(blank=True, default=list, help_text='3x3 homography matrix as nested list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
            options={
                'ordering': ['product', 'sort_order', 'view_label'],
                'unique_together': {('product', 'view_label')},
            },
        ),
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_image', models.ImageField(upload_to='uploads/designs/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='renders/results/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('design_opacity', models.FloatField(default=1.0, help_text='0.0–1.0 opacity of the design layer')),
                ('design_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='products.productview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
